# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [1]:
s = "Hi there Sam!"
s=s.split()
print(s);

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [2]:
planet = "Earth"
diameter = 12742
print('The diameter of  {} is {} kilometers.' .format(planet,diameter));

The diameter of  Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [6]:
lst=[1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
a=lst[3][1][2];
print(a)

['hello']


# Numpy

In [7]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [11]:
import numpy as np
array=np.arange(20,35)
print("Array of the integers from 20 to 35")
print(array)

Array of the integers from 20 to 35
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a, b), axis=0)

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [14]:
import pandas as pd


In [18]:





# initialize list of lists
data = [['tom', 10], ['nick', 15], ['juli', 14]]

# Create the pandas DataFrame
df = pd.DataFrame(columns=['',''])

# print dataframe.
df



Empty DataFrame
Columns: [, ]
Index: []

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [20]:
from datetime import date, timedelta

sdate = date(2023,1,1)   # start date
edate = date(2023,2,10)   # end date

def dates_bwn_twodates(start_date, end_date):
    for n in range(int ((end_date - start_date).days)):
        yield start_date + timedelta(n)
print(dates_bwn_twodates(sdate,edate))

<generator object dates_bwn_twodates at 0x7fddba0e4450>


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [23]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [27]:
# import pandas as pd
import pandas as pd
 
# List1
lists = [[1, 'aaa', 22], [2, 'bbb', 25],[3, 'ccc', 24]]

# creating df object with columns specified 
df = pd.DataFrame(lists)
print(df )


   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
